baseURL = 'http://example.org/'
languageCode = 'pt-br'
title = 'Ana Carolina Gomes da Silva'
theme = 'bulma'

paginate = 5 # Number of posts to show before 

enableRobotsTXT = true # Suggested, it generates a robots.txt
googleAnalytics = "" # Optional, add tracking Id for analytics
disqusShortname = "" # Optional, add Disqus shortname for comments
SectionPagesMenu = "main" # Enable menu system for lazy bloggers

[params]
  theme_variant = "litera" # possible value for the theme_variant `cerulean,cosmo,cyborg,darkly,flatly,journal,litera,lumen,lux,materia,minty,pulse,sandstone,simplex,slate,solar,spacelab,superhero,united,yeti`
  description = "" # Suggested, controls default description meta and landing page
  powered_by = "lingsv" # Optional, controls name display on footer
  hide_author = false # Optional, set true to hide author name on posts
  images = [] # Suggested, controls default OpenGraph images controls author name display on meta tag
  github  = "lingsv" # Optional, to display link to github account in menu bar
  twitter = "carol_gsv" # Optional, to display link to twitter account in menu bar
  linkedin = "anacarolinagsv"

  

